mysql:
  vesta:
    dbtype: mysql
    dbport: 3306
    dbhost: 192.168.188.101
    dbname: vesta
    dbusername: root
    dbpassword: root_yixin
  vesta_data:
    dbtype: mysql
    dbport: 3306
    dbhost: 192.168.155.178
    dbname: vesta_data
    dbusername: root
    dbpassword: mysql
url:
  indexsrv: http://192.168.144.27/vesta/indexmgr/lands
alarm:
  wechat: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=f309e5c3-146a-41b8-bb2f-27f1abcb62a5
rabbitmq:
  address: amqp://guest:guest@192.168.177.83:5672/yx_mq
  exchange: vesta_pblog
  routingkey: rtlogs